---
title: "Hummel Replication"
author: "Dominic Skinnion"
date: "4/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MASS)
library(margins)
library(clubSandwich)
library(stargazer)
library(survival)
library(png)
library(raster)

```

```{r, echo = FALSE}

### Figure 2 Replication

data<-read.csv("../raw-data/datafull_190123.csv")
data<-data[-c(1)]

### Summary Statistics (Appendix, Table 1)

sumstats<-data[,c("polity2","regimechange","democracy","death","agepre","agepost","tenpre","tenpost","gdppcln","personal","otherirreg","allcoup_bin")]
#stargazer(sumstats,out="sumstats", label="tab:sumstats",title="Summary Statistics")


### H0 Analysis - effect of leader death on different measures of political change.  

#DV: Polity

#1-year DV (Appendix, Table 2)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE )

d1<-subset(nondem,death_for1==0 )
d1<-subset(d1,is.na(polity_for1)==FALSE)

d<-d1
m1<- lm(polity_for1~death,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m2<- lm(polity_for1~death+polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
pol1_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(polity_for1~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
pol1_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for1) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- lm(polity_for1~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- lm(polity_for1~death+agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))


d1<-subset(d1,is.na(ccode)==FALSE &is.na(year)==FALSE)
d<-d1
m6<- lm(polity_for1~death+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m7<- lm(polity_for1~death+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m7)
pol1_noage_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- lm(polity_for1~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m8)
pol1_age_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for1) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- lm(polity_for1~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m9,cluster=d$ccode,type="CR1")
se9<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- lm(polity_for1~death+agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m10,cluster=d$ccode,type="CR1")
se10<-sqrt(diag(vc))

plotty_pol1<-rbind(pol1_noage_nofe,pol1_age_nofe,pol1_noage_fe,pol1_age_fe)



#5-year DV (Appendix, Table 3)


nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE )

d5<-subset(nondem,death_for5==0 )
d5<-subset(d5,is.na(polity_for5)==FALSE)

d<-d5
m1<- lm(polity_for5~death,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m2<- lm(polity_for5~death+polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
pol5_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(polity_for5~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
pol5_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for5) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- lm(polity_for5~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- lm(polity_for5~death+agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))


d5<-subset(d5,is.na(ccode)==FALSE &is.na(year)==FALSE)

d<-d5
m6<- lm(polity_for5~death+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m7<- lm(polity_for5~death+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m7)
pol5_noage_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- lm(polity_for5~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m8)
pol5_age_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for5) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- lm(polity_for5~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m9,cluster=d$ccode,type="CR1")
se9<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- lm(polity_for5~death+agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m10,cluster=d$ccode,type="CR1")
se10<-sqrt(diag(vc))

plotty_pol5<-rbind(pol5_noage_nofe,pol5_age_nofe,pol5_noage_fe,pol5_age_fe)



#10-year DV (Appendix, Table 4)


nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE )

d10<-subset(nondem,death_for10==0 )
d10<-subset(d10,is.na(polity_for10)==FALSE)

d<-d10
m1<- lm(polity_for10~death,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m2<- lm(polity_for10~death+polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
pol10_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(polity_for10~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
pol10_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for10) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- lm(polity_for10~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- lm(polity_for10~death+agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))


d10<-subset(d10,is.na(ccode)==FALSE &is.na(year)==FALSE)

d<-d10
m6<- lm(polity_for10~death+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m7<- lm(polity_for10~death+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m7)
pol10_noage_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- lm(polity_for10~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m8)
pol10_age_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for10) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- lm(polity_for10~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m9,cluster=d$ccode,type="CR1")
se9<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- lm(polity_for10~death+agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m10,cluster=d$ccode,type="CR1")
se10<-sqrt(diag(vc))

plotty_pol10<-rbind(pol10_noage_nofe,pol10_age_nofe,pol10_noage_fe,pol10_age_fe)




## DV: Democratization 


#1-year DV (Appendix, Table 5)

nondem<-subset(data,democracy_lag1==0)
nondem<-subset(nondem, is.na(death)==FALSE )

d1<-subset(nondem,death_for1==0 )
d1<-subset(d1,is.na(democracy_for1)==FALSE)

d<-d1
m1<- glm(democracy_for1~death,data=d,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m2<- glm(democracy_for1~death+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
dem1_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- glm(democracy_for1~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
dem1_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(democracy_for1) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- glm(democracy_for1~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- glm(democracy_for1~death+agepre+tenpre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))


d1<-subset(d1,is.na(ccode)==FALSE &is.na(year)==FALSE)

d<-d1
m6<- clogit(democracy_for1~death+strata(ccode),data=d)

d<-subset(d1,is.na(polity_lag1)==FALSE)
m7<- clogit(democracy_for1~death+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m7)[1]
se<-coef(summary(m7))[1,3]
dem1_noage_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- clogit(democracy_for1~death+agepre+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m8)[1]
se<-coef(summary(m8))[1,3]
dem1_age_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(nondem,is.na(democracy_for1) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- clogit(democracy_for1~death+agepre+polity_lag1+strata(ccode),data=d)


d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- clogit(democracy_for1~death+agepre+tenpre+polity_lag1+strata(ccode),data=d)


plotty_dem1<-rbind(dem1_noage_nofe,dem1_age_nofe,dem1_noage_fe,dem1_age_fe)


## 5-year DV (Appendix, Table 6)

nondem<-subset(data,democracy_lag1==0)
nondem<-subset(nondem, is.na(death)==FALSE )

d5<-subset(nondem,death_for5==0 )
d5<-subset(d5,is.na(democracy_for5)==FALSE)

d<-d5
m1<- glm(democracy_for5~death,data=d,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m2<- glm(democracy_for5~death+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
dem5_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- glm(democracy_for5~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
dem5_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(democracy_for5) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- glm(democracy_for5~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- glm(democracy_for5~death+agepre+tenpre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))


d5<-subset(d5,is.na(ccode)==FALSE &is.na(ccode)==FALSE)

d<-d5
m6<- clogit(democracy_for5~death+strata(ccode),data=d)

d<-subset(d5,is.na(polity_lag1)==FALSE)
m7<- clogit(democracy_for5~death+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m7)[1]
se<-coef(summary(m7))[1,3]
dem5_noage_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- clogit(democracy_for5~death+agepre+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m8)[1]
se<-coef(summary(m8))[1,3]
dem5_age_fe<-c(coef,coef+1.96*se,coef-1.96*se)


d<-subset(nondem,is.na(democracy_for5) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- clogit(democracy_for5~death+agepre+polity_lag1+strata(ccode),data=d)

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- clogit(democracy_for5~death+agepre+tenpre+polity_lag1+strata(ccode),data=d)

plotty_dem5<-rbind(dem5_noage_nofe,dem5_age_nofe,dem5_noage_fe,dem5_age_fe)


## 10-year DV (Appendix, Table 7)

nondem<-subset(data,democracy_lag1==0)
nondem<-subset(nondem, is.na(death)==FALSE )

d10<-subset(nondem,death_for10==0 )
d10<-subset(d10,is.na(democracy_for10)==FALSE)

d<-d10
m1<- glm(democracy_for10~death,data=d,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m2<- glm(democracy_for10~death+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
dem10_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- glm(democracy_for10~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
dem10_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(democracy_for10) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- glm(democracy_for10~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- glm(democracy_for10~death+agepre+tenpre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))


d5<-subset(d10,is.na(ccode)==FALSE &is.na(ccode)==FALSE)

d<-d10
m6<- clogit(democracy_for10~death+strata(ccode),data=d)

d<-subset(d10,is.na(polity_lag1)==FALSE)
m7<- clogit(democracy_for10~death+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m7)[1]
se<-coef(summary(m7))[1,3]
dem10_noage_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- clogit(democracy_for10~death+agepre+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m8)[1]
se<-coef(summary(m8))[1,3]
dem10_age_fe<-c(coef,coef+1.96*se,coef-1.96*se)


d<-subset(nondem,is.na(democracy_for10) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- clogit(democracy_for10~death+agepre+polity_lag1+strata(ccode),data=d)

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- clogit(democracy_for10~death+agepre+tenpre+polity_lag1+strata(ccode),data=d)

plotty_dem10<-rbind(dem10_noage_nofe,dem10_age_nofe,dem10_noage_fe,dem10_age_fe)


### Regime Change

## 1-Year DV (Appendix, Table 8)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE )

d1<-subset(nondem,death_for1==0 )
d1<-subset(d1,is.na(regimechange_for1)==FALSE)

d<-d1
m1<- glm(regimechange_for1~death,data=d,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m2<- glm(regimechange_for1~death+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
rc1_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- glm(regimechange_for1~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
rc1_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(regimechange_for1) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- glm(regimechange_for1~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- glm(regimechange_for1~death+agepre+tenpre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))


d1<-subset(d1,is.na(ccode)==FALSE &is.na(year)==FALSE)

d<-d1
m6<- clogit(regimechange_for1~death+strata(ccode),data=d)

d<-subset(d1,is.na(polity_lag1)==FALSE)
m7<- clogit(regimechange_for1~death+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m7)[1]
se<-coef(summary(m7))[1,3]
rc1_noage_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- clogit(regimechange_for1~death+agepre+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m8)[1]
se<-coef(summary(m8))[1,3]
rc1_age_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(nondem,is.na(regimechange_for1) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- clogit(democracy_for1~death+agepre+polity_lag1+strata(ccode),data=d)


d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- clogit(regimechange_for1~death+agepre+tenpre+polity_lag1+strata(ccode),data=d)


plotty_rc1<-rbind(rc1_noage_nofe,rc1_age_nofe,rc1_noage_fe,rc1_age_fe)


## 5-Yr DV (Appendix, Table 5)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE )

d5<-subset(nondem,death_for5==0 )
d5<-subset(d5,is.na(regimechange_for5)==FALSE)

d<-d5
m1<- glm(regimechange_for5~death,data=d,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m2<- glm(regimechange_for5~death+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
rc5_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- glm(regimechange_for5~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
rc5_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(regimechange_for5) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- glm(regimechange_for5~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- glm(regimechange_for5~death+agepre+tenpre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d5<-subset(d5,is.na(ccode)==FALSE &is.na(year)==FALSE)
d<-d5

m6<- clogit(regimechange_for5~death+strata(ccode),data=d)

d<-subset(d5,is.na(polity_lag1)==FALSE)
m7<- clogit(regimechange_for5~death+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m7)[1]
se<-coef(summary(m7))[1,3]
rc5_noage_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- clogit(regimechange_for5~death+agepre+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m8)[1]
se<-coef(summary(m8))[1,3]
rc5_age_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(nondem,is.na(regimechange_for5) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- clogit(democracy_for5~death+agepre+polity_lag1+strata(ccode),data=d)


d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- clogit(regimechange_for5~death+agepre+tenpre+polity_lag1+strata(ccode),data=d)


plotty_rc5<-rbind(rc5_noage_nofe,rc5_age_nofe,rc5_noage_fe,rc5_age_fe)


## 10-yr DV (Appendix, Table 10)


nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE )

d10<-subset(nondem,death_for10==0 )
d10<-subset(d10,is.na(regimechange_for10)==FALSE)

d<-d10
m1<- glm(regimechange_for10~death,data=d,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m2<- glm(regimechange_for10~death+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
rc10_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- glm(regimechange_for10~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
rc10_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(regimechange_for10) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- glm(regimechange_for10~death+agepre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- glm(regimechange_for10~death+agepre+tenpre+polity_lag1,data=d,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d5<-subset(d10,is.na(ccode)==FALSE &is.na(year)==FALSE)
d<-d10

m6<- clogit(regimechange_for10~death+strata(ccode),data=d)

d<-subset(d10,is.na(polity_lag1)==FALSE)
m7<- clogit(regimechange_for10~death+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m7)[1]
se<-coef(summary(m7))[1,3]
rc10_noage_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- clogit(regimechange_for10~death+agepre+polity_lag1+strata(ccode),data=d)
coef<-coefficients(m8)[1]
se<-coef(summary(m8))[1,3]
rc10_age_fe<-c(coef,coef+1.96*se,coef-1.96*se)

d<-subset(nondem,is.na(regimechange_for10) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- clogit(democracy_for10~death+agepre+polity_lag1+strata(ccode),data=d)


d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- clogit(regimechange_for10~death+agepre+tenpre+polity_lag1+strata(ccode),data=d)


plotty_rc10<-rbind(rc10_noage_nofe,rc10_age_nofe,rc10_noage_fe,rc10_age_fe)


### Absolute change in polity


#1-year DV (Appendix, Table 11)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE )

d1<-subset(nondem,death_for1==0 )
d1<-subset(d1,is.na(abspolchange_for1)==FALSE)

d<-d1
m1<- lm(abspolchange_for1~death,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m2<- lm(abspolchange_for1~death+polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
abs1_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(abspolchange_for1~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
abs1_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(abspolchange_for1) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- lm(abspolchange_for1~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- lm(abspolchange_for1~death+agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d1<-subset(d1,is.na(ccode)==FALSE &is.na(year)==FALSE)
d<-d1
m6<- lm(abspolchange_for1~death+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m7<- lm(abspolchange_for1~death+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m7)
abs1_noage_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- lm(abspolchange_for1~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m8)
abs1_age_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for1) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- lm(abspolchange_for1~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m9,cluster=d$ccode,type="CR1")
se9<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- lm(abspolchange_for1~death+agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m10,cluster=d$ccode,type="CR1")
se10<-sqrt(diag(vc))

plotty_abs1<-rbind(abs1_noage_nofe,abs1_age_nofe,abs1_noage_fe,abs1_age_fe)



#5-year DV (Appendix, Table 12)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE )

d5<-subset(nondem,death_for5==0 )
d5<-subset(d5,is.na(abspolchange_for5)==FALSE)

d<-d5
m1<- lm(abspolchange_for5~death,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m2<- lm(abspolchange_for5~death+polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
abs5_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(abspolchange_for5~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
abs5_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(abspolchange_for5) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- lm(abspolchange_for5~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- lm(abspolchange_for5~death+agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d5<-subset(d1,is.na(ccode)==FALSE &is.na(year)==FALSE)
d<-d5
m6<- lm(abspolchange_for5~death+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m7<- lm(abspolchange_for5~death+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m7)
abs5_noage_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- lm(abspolchange_for5~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m8)
abs5_age_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for5) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- lm(abspolchange_for5~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m9,cluster=d$ccode,type="CR1")
se9<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- lm(abspolchange_for5~death+agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m10,cluster=d$ccode,type="CR1")
se10<-sqrt(diag(vc))

plotty_abs5<-rbind(abs5_noage_nofe,abs5_age_nofe,abs5_noage_fe,abs5_age_fe)


## 10 year DV (Appendix, Table 13)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE )

d10<-subset(nondem,death_for5==0 )
d10<-subset(d10,is.na(abspolchange_for10)==FALSE)

d<-d10
m1<- lm(abspolchange_for10~death,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m2<- lm(abspolchange_for10~death+polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m2)
abs10_noage_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(abspolchange_for10~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m3)
abs10_age_nofe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(abspolchange_for10) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m4<- lm(abspolchange_for10~death+agepre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m5<- lm(abspolchange_for10~death+agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d10<-subset(d10,is.na(ccode)==FALSE &is.na(year)==FALSE)
d<-d10
m6<- lm(abspolchange_for10~death+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m7<- lm(abspolchange_for10~death+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m7)
abs10_noage_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m8<- lm(abspolchange_for10~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))
se<-sqrt(diag(vc))
coef<-coefficients(m8)
abs10_age_fe<-c(coef[2],coef[2]+1.96*se[2],coef[2]-1.96*se[2])

d<-subset(nondem,is.na(polity_for10) ==FALSE & is.na(ccode)==FALSE &is.na(year)==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m9<- lm(abspolchange_for10~death+agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m9,cluster=d$ccode,type="CR1")
se9<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m10<- lm(abspolchange_for10~death+agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m10,cluster=d$ccode,type="CR1")
se10<-sqrt(diag(vc))

plotty_abs10<-rbind(abs10_noage_nofe,abs10_age_nofe,abs10_noage_fe,abs10_age_fe)

```

```{r, echo = FALSE}

###H0 Plot - Figure 2 in the main article. 

png("../graphics/figH0.png")

#shapes<-c(0, 1, 15, 16)
shapes <- 20
#colors <- c("#88CCEE", "#117733", "#332288", "#AA4499")
colors<-c("gray75", "gray50","gray25","gray0")

plot_1<-plotty_pol1
plot_5<-plotty_pol5
plot_10<-plotty_pol10


plot(x=plot_1[,1],y=c(73:70),xlim=c(-5,5),ylim=c(1,73),pch=shapes,col=colors,yaxt="n",xlab="Coefficient Estimate",ylab="",cex=0.8)
segments(x0=plot_1[,2],y0=c(73:70),x1=plot_1[,3],y1=c(73:70),col=colors)
points(x=plot_5[,1],y=c(67:64),pch=shapes,col=colors)
segments(x0=plot_5[,2],y0=c(67:64),x1=plot_5[,3],y1=c(67:64),col=colors)
points(x=plot_10[,1],y=c(61:58),pch=shapes,col=colors)
segments(x0=plot_10[,2],y0=c(61:58),x1=plot_10[,3],y1=c(61:58),col=colors)
abline(h=56)

plot_1<-plotty_dem1
plot_5<-plotty_dem5
plot_10<-plotty_dem10
points(x=plot_1[,1],y=c(54:51),pch=shapes,col=colors)
segments(x0=plot_1[,2],y0=c(54:51),x1=plot_1[,3],y1=c(54:51),col=colors)
points(x=plot_5[,1],y=c(48:45),pch=shapes,col=colors)
segments(x0=plot_5[,2],y0=c(48:45),x1=plot_5[,3],y1=c(48:45),col=colors)
points(x=plot_10[,1],y=c(42:39),pch=shapes,col=colors)
segments(x0=plot_10[,2],y0=c(42:39),x1=plot_10[,3],y1=c(42:39),col=colors)
abline(h=37)

plot_1<-plotty_rc1
plot_5<-plotty_rc5
plot_10<-plotty_rc10
points(x=plot_1[,1],y=c(35:32),pch=shapes,col=colors)
segments(x0=plot_1[,2],y0=c(35:32),x1=plot_1[,3],y1=c(35:32),col=colors)
points(x=plot_5[,1],y=c(29:26),pch=shapes,col=colors)
segments(x0=plot_5[,2],y0=c(29:26),x1=plot_5[,3],y1=c(29:26),col=colors)
points(x=plot_10[,1],y=c(23:20),pch=shapes,col=colors)
segments(x0=plot_10[,2],y0=c(23:20),x1=plot_10[,3],y1=c(23:20),col=colors)
abline(h=18)

plot_1<-plotty_abs1
plot_5<-plotty_abs5
plot_10<-plotty_abs10
points(x=plot_1[,1],y=c(16:13),pch=shapes,col=colors)
segments(x0=plot_1[,2],y0=c(16:13),x1=plot_1[,3],y1=c(16:13),col=colors)
points(x=plot_5[,1],y=c(10:7),pch=shapes,col=colors)
segments(x0=plot_5[,2],y0=c(10:7),x1=plot_5[,3],y1=c(10:7),col=colors)
points(x=plot_10[,1],y=c(4:1),pch=shapes,col=colors)
segments(x0=plot_10[,2],y0=c(4:1),x1=plot_10[,3],y1=c(4:1),col=colors)

abline(v=0,lty=2)

axis(2, at=c(2.5,7.5,12.5,21.5,27.5,33.5,40.5,46.5,52.5,59.5,65.5,71.5),tick=FALSE,labels=rep(c("10yr","5yr","1yr"),4), las=2,cex=0.8)
legend(2.75,72.5,c("No age, no FE","Age, no FE","No age, FE","Age, FE"), pch=shapes,col=colors,text.font=3,cex=0.8)
abline(v=0,lty=2)

text(-5.25,59.5,"DV: Polity",vfont=c("sans serif","bold italic"),pos=4)

text(-5.25,40.5,"DV: Democracy",vfont=c("sans serif","bold italic"),pos=4)
text(-5.25,21.5,"DV: Regime Change",vfont=c("sans serif","bold italic"),pos=4)
text(-5.25,3.5,"DV: Absolute",vfont=c("sans serif","bold italic"),pos=4)
text(-5.15,0,"Polity Change",vfont=c("sans serif","bold italic"),pos=4)
dev.off()
```

```{r, echo = FALSE, fig.width=8, fig.height=8}

### Figure 1 Replication

death<-subset(data,death==1)

png(file="../graphics/fig_prepostpolity1.png")
plot(death$polity_lag1,death$polity_for1,xlim=c(-10,10),ylim=c(-10,10),ylab="Polity, 1 year after",xlab="Polity, year before")
abline(a=0,b=1)
abline(a=5,b=1,lty=5)
abline(a=-5,b=1,lty=5)
s<-subset(death, abs(polity_for1-polity_lag1)>5)

text(8,-8.5,"Greece 1936",cex=0.75) 
text(4,-5.5,"Ethiopia 1930",cex=0.75) 
text(4.2,-2.5,"Comoros 1998",cex=0.75) 
text(2,-9.5,"Paraguay 1940",cex=0.75) 

text(-7,1.5,"Spain 1975",cex=0.75) 
text(-5,8.5,"Croatia 1999",cex=0.75) 
text(-9,0.5,"Greece 1941",cex=0.75) 
text(-9,-1.5,"Bulgaria 1943",cex=0.75) 
text(-6,4.5,"Nigeria 1998",cex=0.75) 
text(-6.1,0.5,"Yemen 1962",cex=0.75) 
dev.off()

png(file="../graphics/fig_prepostpolity5.png")
plot(death$polity_lag1,death$polity_for5,xlim=c(-10,10),ylim=c(-10,10),ylab="Ave. Polity, 5 years after",xlab="Polity, year before")
abline(a=0,b=1)
abline(a=5,b=1,lty=5)
abline(a=-5,b=1,lty=5)
s<-subset(death, abs(polity_for5-polity_lag1)>5)
text(-7,7.1,"Spain 1975",cex=0.75) 
text(-5,8.5,"Croatia 1999",cex=0.75) 
text(-8,5.3,"Greece 1941",cex=0.75) 
text(-6,4.5,"Nigeria 1998",cex=0.75) 

text(8,-1.3,"Colombia 1884",cex=0.75) 
text(2,-9.5,"Paraguay 1940",cex=0.75) 
text(6,-5.5,"Argentina 1974",cex=0.75) 
text(8,-6.9,"Greece 1936",cex=0.75) 
text(4,-4.5,"Ethiopia 1930",cex=0.75) 
dev.off()


png(file="../graphics/fig_prepostpolity10.png")
plot(death$polity_lag1,death$polity_for10,xlim=c(-10,10),ylim=c(-10,10),ylab="Ave. Polity, 10 years after",xlab="Polity, year before")
abline(a=0,b=1)
abline(a=5,b=1,lty=5)
abline(a=-5,b=1,lty=5)
s<-subset(death, abs(polity_for10-polity_lag1)>5)

text(2,-5.1,"Guatemala 1926",cex=0.6) 
text(8,0.8,"Colombia 1882",cex=0.6) 
text(8,-2.4,"Colombia 1884",cex=0.6) 
text(2,-8,"Paraguay 1940",cex=0.6) 
text(6,-4.4,"Argentina 1974",cex=0.6) 
text(8.6,2.1,"Uruguay 1965",cex=0.6) 
text(8,-1.1,"Uruguay 1967",cex=0.6) 
text(8,-0.3,"Greece 1936",cex=0.6) 
text(5.6,-1.9,"Sierra Leone 1964",cex=0.6) 

text(-7.6,-1.4,"Guyana 1985",cex=0.6) 
text(-7,8.7,"Spain 1975",cex=0.6) 
text(-9.5,-2.3,"Portugal 1968",cex=0.6) 
text(-9.5,-0.9,"Albania 1985",cex=0.6) 
text(-5,9,"Croatia 1999",cex=0.6) 
text(-8,5.7,"Greece 1941",cex=0.6) 
text(-7,-0.5,"Russia 1985",cex=0.6) 
text(-7,0.5,"Niger 1987",cex=0.6) 
text(-6,4.5,"Nigeria 1998",cex=0.6) 
text(-1,5.6,"Taiwan",cex=0.6) 
dev.off()

```


```{r}

### Figure 1 Replication Continued

png("../graphics/fig_1.png", res = 200, units = "in", width = 10, height = 10)

plot(0:8, 0:8, type = "n", xaxt = "n", yaxt = "n", xlab = "", ylab = "")
rasterImage(readPNG(source="../graphics/fig_prepostpolity1.png"), 0, 4, 4, 8)
rasterImage(readPNG(source="../graphics/fig_prepostpolity5.png"), 4, 4, 8, 8)
rasterImage(readPNG(source="../graphics/fig_prepostpolity10.png"), 0, 0, 4, 4)
text(0, 7.6, "A", cex=2)
text(4, 7.6, "B", cex=2)
text(0, 3.8, "C", cex=2)
dev.off()

```

```{r}

### Figure 3 Replication

####### H1 Analysis:  Effect of leader death and age on political liberalization ########

# 1-Year DV (Appendix, Table 14)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE )

d1<-subset(nondem,death_for1==0 )
d1<-subset(d1,is.na(polity_for1)==FALSE)

d<-d1
m1<- lm(polity_for1~death*agepre,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m2<- lm(polity_for1~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
a<-seq(quantile(d$agepre,0.1, na.rm=TRUE),quantile(d$agepre,0.9,na.rm=TRUE),1)
marg1_nofe<-margins(m2,at=list(agepre=a),vcov=vc,variables="death")

d<-subset(nondem,is.na(polity_for1) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(polity_for1~death*agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m4<- lm(polity_for1~death*agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d1<-subset(d1,is.na(ccode)==FALSE &is.na(year)==FALSE)

d<-d1
m5<- lm(polity_for1~death*agepre+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE)
m6<- lm(polity_for1~death*agepre + polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))
a<-seq(quantile(d$agepre,0.1, na.rm=TRUE),quantile(d$agepre,0.9,na.rm=TRUE),1)
marg1_fe<-margins(m6,at=list(agepre=a),vcov=vc,variables="death")

d<-subset(nondem,is.na(polity_for1) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m7<- lm(polity_for1~death*agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))

d<-subset(d1,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m8<- lm(polity_for1~death*agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))


# 5-Year DV (Appendix, Table 15)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE )

d5<-subset(nondem,death_for5==0 )
d5<-subset(d1,is.na(polity_for5)==FALSE)

d<-d5
m1<- lm(polity_for5~death*agepre,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m2<- lm(polity_for5~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
a<-seq(quantile(d$agepre,0.1, na.rm=TRUE),quantile(d$agepre,0.9,na.rm=TRUE),1)
marg5_nofe<-margins(m2,at=list(agepre=a),vcov=vc,variables="death")

d<-subset(nondem,is.na(polity_for5) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(polity_for5~death*agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m4<- lm(polity_for5~death*agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d5<-subset(d5,is.na(ccode)==FALSE &is.na(year)==FALSE)

d<-d5
m5<- lm(polity_for5~death*agepre+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE)
m6<- lm(polity_for5~death*agepre + polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))
a<-seq(quantile(d$agepre,0.1, na.rm=TRUE),quantile(d$agepre,0.9,na.rm=TRUE),1)
marg5_fe<-margins(m6,at=list(agepre=a),vcov=vc,variables="death")

d<-subset(nondem,is.na(polity_for5) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m7<- lm(polity_for5~death*agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))

d<-subset(d5,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m8<- lm(polity_for5~death*agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))


# 10-Year DV (Appendix, Table 16)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE )

d10<-subset(nondem,death_for10==0 )
d10<-subset(d1,is.na(polity_for10)==FALSE)

d<-d10
m1<- lm(polity_for10~death*agepre,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m2<- lm(polity_for10~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
a<-seq(quantile(d$agepre,0.1, na.rm=TRUE),quantile(d$agepre,0.9,na.rm=TRUE),1)
marg10_nofe<-margins(m2,at=list(agepre=a),vcov=vc,variables="death")

d<-subset(nondem,is.na(polity_for10) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m3<- lm(polity_for10~death*agepre+polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m4<- lm(polity_for10~death*agepre+tenpre+polity_lag1,data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d10<-subset(d10,is.na(ccode)==FALSE &is.na(year)==FALSE)

d<-d10
m5<- lm(polity_for10~death*agepre+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se10<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE)
m6<- lm(polity_for10~death*agepre + polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))
a<-seq(quantile(d$agepre,0.1, na.rm=TRUE),quantile(d$agepre,0.9,na.rm=TRUE),1)
marg10_fe<-margins(m6,at=list(agepre=a),vcov=vc,variables="death")

d<-subset(nondem,is.na(polity_for10) ==FALSE & is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE)
m7<- lm(polity_for10~death*agepre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m7,cluster=d$ccode,type="CR1")
se7<-sqrt(diag(vc))

d<-subset(d10,is.na(polity_lag1)==FALSE & is.na(agepre)==FALSE &is.na(tenpre)==FALSE)
m8<- lm(polity_for10~death*agepre+tenpre+polity_lag1+factor(ccode)+factor(year),data=d)
vc<-vcovCR(m8,cluster=d$ccode,type="CR1")
se8<-sqrt(diag(vc))

### Plot for H1 : Figure 3 in main article 

confi<-function(x,length,lev){
  confi<-confint(subset(x, agepre==summary(x)$agepre[1]),level=lev)	
  for(i in c(summary(x)$agepre[1:length])){
    a<-i
    confi<-rbind(confi,confint(subset(x, agepre==a))	)
  }
  return(data.frame(confi))
}


png(file="../graphics/fig3.png")
par(mfrow=c(3,2))
len<-nrow(summary(marg1_nofe))
confintty<-confi(marg1_nofe,len,0.9)
plot(x=summary(marg1_nofe)$agepre,y=as.numeric(summary(marg1_nofe)$AME),pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-2,1.5),cex=0.8, main="1-Year DV, No Fixed Effects")
segments(x0=summary(marg1_nofe)$agepre,
         y0=confintty$lower[1:len],
         x1=summary(marg1_nofe)$agepre,
         y1=confintty$upper[1:len])
abline(h=0)

len<-nrow(summary(marg1_fe))
confintty<-confi(marg1_fe,len,0.9)
plot(x=summary(marg1_fe)$agepre,y=as.numeric(summary(marg1_fe)$AME),pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-2,1.5),cex=0.8, main="1-Year DV, Fixed Effects")
segments(x0=summary(marg1_fe)$agepre,
         y0=confintty$lower[1:len],
         x1=summary(marg1_fe)$agepre,
         y1=confintty$upper[1:len])
abline(h=0)

len<-nrow(summary(marg5_nofe))
confintty<-confi(marg5_nofe,len,0.9)
plot(x=summary(marg5_nofe)$agepre,y=as.numeric(summary(marg5_nofe)$AME),pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-2,1.5),cex=0.8, main="5-Year DV, No Fixed Effects")
segments(x0=summary(marg5_nofe)$agepre,
         y0=confintty$lower[1:len],
         x1=summary(marg5_nofe)$agepre,
         y1=confintty$upper[1:len])
abline(h=0)

len<-nrow(summary(marg5_fe))
confintty<-confi(marg5_fe,len,0.9)
plot(x=summary(marg5_fe)$agepre,y=as.numeric(summary(marg5_fe)$AME),pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-2,1.5),cex=0.8, main="5-Year DV, Fixed Effects")
segments(x0=summary(marg5_fe)$agepre,
         y0=confintty$lower[1:len],
         x1=summary(marg5_fe)$agepre,
         y1=confintty$upper[1:len])
abline(h=0)

len<-nrow(summary(marg10_nofe))
confintty<-confi(marg10_nofe,len,0.9)
plot(x=summary(marg10_nofe)$agepre,y=as.numeric(summary(marg10_nofe)$AME),pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-2,1.5),cex=0.8, main="10-Year DV, No Fixed Effects")
segments(x0=summary(marg10_nofe)$agepre,
         y0=confintty$lower[1:len],
         x1=summary(marg10_nofe)$agepre,
         y1=confintty$upper[1:len])
abline(h=0)

len<-nrow(summary(marg10_fe))
confintty<-confi(marg10_fe,len,0.9)
plot(x=summary(marg10_fe)$agepre,y=as.numeric(summary(marg10_fe)$AME),pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-2,1.5),cex=0.8, main="10-Year DV, Fixed Effects")
segments(x0=summary(marg10_fe)$agepre,
         y0=confintty$lower[1:len],
         x1=summary(marg10_fe)$agepre,
         y1=confintty$upper[1:len])
abline(h=0)
dev.off()

```

```{r}

### Figure 4 Replication

######### Hypothesis 2a: Effect of leader death and age in personalist vs non-personalist regimes


# 1-Year DV (Appendix, Table 17)

## Basic Specification 

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)

d1<-subset(nondem,death_for1==0 )
d1<-subset(d1,is.na(polity_for1)==FALSE & is.na(polity_lag1)==FALSE)
d1p<-subset(d1,personal_lag1==1)
d1n<-subset(d1,personal_lag1==0)

d<-d1p
m1<- lm(polity_for1~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d1p<-subset(d1p,is.na(year)==FALSE)
d<-d1p
m2<- lm(polity_for1~death*agepre+ polity_lag1 +factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d1n
m3<- lm(polity_for1~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d1n<-subset(d1n,is.na(year)==FALSE)
d<-d1n
m4<- lm(polity_for1~death*agepre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d1
m5<- lm(polity_for1~death*agepre*personal_lag1 + polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))
a<-seq(quantile(d$agepre,0.1, na.rm=TRUE),quantile(d$agepre,0.9,na.rm=TRUE),1)
marg1_nofe<-margins(m5,at=list(personal_lag1=0:1,agepre=a),vcov=vc,variables="death")


d1<-subset(d1,is.na(year)==FALSE)
d<-d1
m6<- lm(polity_for1~death*agepre*personal_lag1+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))
marg1_fe<-margins(m6,at=list(personal_lag1=0:1,agepre=a),vcov=vc,variables="death")


## Tenure Specification (Appendix, Table 18)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)

d1<-subset(nondem,death_for1==0 )
d1<-subset(d1,is.na(polity_for1)==FALSE & is.na(polity_lag1)==FALSE & is.na(tenpre)==FALSE)
d1p<-subset(d1,personal_lag1==1)
d1n<-subset(d1,personal_lag1==0)

d<-d1p
m1<- lm(polity_for1~death*agepre + tenpre+ polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d1p<-subset(d1p,is.na(year)==FALSE)
d<-d1p
m2<- lm(polity_for1~death*agepre+tenpre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d1n
m3<- lm(polity_for1~death*agepre + tenpre+ polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d1n<-subset(d1n,is.na(year)==FALSE)
d<-d1n
m4<- lm(polity_for1~death*agepre+tenpre+polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d1
m5<- lm(polity_for1~death*agepre*personal_lag1 +tenpre+ polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d1<-subset(d1,is.na(year)==FALSE)
d<-d1
m6<- lm(polity_for1~death*agepre*personal_lag1+tenpre+polity_lag1+ factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

## Basic Specification, Full Sample (Appendix, Table 19)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)


d1<-subset(d1,is.na(polity_lag1)==FALSE)
d1p<-subset(d1,personal_lag1==1)
d1n<-subset(d1,personal_lag1==0)

d<-d1p
m1<- lm(polity_for1~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d1p<-subset(d1p,is.na(year)==FALSE)
d<-d1p
m2<- lm(polity_for1~death*agepre+ polity_lag1 +factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d1n
m3<- lm(polity_for1~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d1n<-subset(d1n,is.na(year)==FALSE)
d<-d1n
m4<- lm(polity_for1~death*agepre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d1
m5<- lm(polity_for1~death*agepre*personal_lag1 + polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d1<-subset(d1,is.na(year)==FALSE)
d<-d1
m6<- lm(polity_for1~death*agepre*personal_lag1+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))


##### 5-Year DV

## Basic Specification (Appendix, Table 20)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)

d5<-subset(nondem,death_for5==0 )
d5<-subset(d5,is.na(polity_for5)==FALSE & is.na(polity_lag1)==FALSE)
d5p<-subset(d5,personal_lag1==1)
d5n<-subset(d5,personal_lag1==0)

d<-d5p
m1<- lm(polity_for5~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d5p<-subset(d5p,is.na(year)==FALSE)
d<-d5p
m2<- lm(polity_for5~death*agepre+ polity_lag1 +factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d5n
m3<- lm(polity_for5~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d5n<-subset(d5n,is.na(year)==FALSE)
d<-d5n
m4<- lm(polity_for5~death*agepre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d5
m5<- lm(polity_for5~death*agepre*personal_lag1 + polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))
marg5_nofe<-margins(m5,at=list(personal_lag1=0:1,agepre=a),vcov=vc,variables="death")


d5<-subset(d5,is.na(year)==FALSE)
d<-d5
m6<- lm(polity_for5~death*agepre*personal_lag1+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))
marg5_fe<-margins(m6,at=list(personal_lag1=0:1,agepre=a),vcov=vc,variables="death")


## Tenure Specification (Appendix, Table 21)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)

d5<-subset(nondem,death_for5==0 )
d5<-subset(d5,is.na(polity_for5)==FALSE & is.na(polity_lag1)==FALSE & is.na(tenpre)==FALSE)
d5p<-subset(d5,personal_lag1==1)
d5n<-subset(d5,personal_lag1==0)

d<-d5p
m1<- lm(polity_for5~death*agepre + tenpre+ polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d5p<-subset(d5p,is.na(year)==FALSE)
d<-d5p
m2<- lm(polity_for5~death*agepre+tenpre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d5n
m3<- lm(polity_for5~death*agepre + tenpre+ polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d5n<-subset(d5n,is.na(year)==FALSE)
d<-d5n
m4<- lm(polity_for5~death*agepre+tenpre+polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d5
m5<- lm(polity_for5~death*agepre*personal_lag1 +tenpre+ polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d5<-subset(d5,is.na(year)==FALSE)
d<-d5
m6<- lm(polity_for5~death*agepre*personal_lag1+tenpre+polity_lag1+ factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))


## Basic Specification, Full Sample  (Appendix, Table 22)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)


d5<-subset(d5,is.na(polity_lag1)==FALSE)
d5p<-subset(d5,personal_lag1==1)
d5n<-subset(d5,personal_lag1==0)

d<-d5p
m1<- lm(polity_for5~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d5p<-subset(d5p,is.na(year)==FALSE)
d<-d5p
m2<- lm(polity_for5~death*agepre+ polity_lag1 +factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d5n
m3<- lm(polity_for5~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d5n<-subset(d5n,is.na(year)==FALSE)
d<-d5n
m4<- lm(polity_for5~death*agepre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d5
m5<- lm(polity_for5~death*agepre*personal_lag1 + polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d5<-subset(d5,is.na(year)==FALSE)
d<-d5
m6<- lm(polity_for5~death*agepre*personal_lag1+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

### 10-Year DV

## Basic Specification (Appendix, Table 23)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)

d10<-subset(nondem,death_for10==0 )
d10<-subset(d10,is.na(polity_for10)==FALSE & is.na(polity_lag1)==FALSE)
d10p<-subset(d10,personal_lag1==1)
d10n<-subset(d10,personal_lag1==0)

d<-d10p
m1<- lm(polity_for10~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d10p<-subset(d10p,is.na(year)==FALSE)
d<-d10p
m2<- lm(polity_for10~death*agepre+ polity_lag1 +factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d10n
m3<- lm(polity_for10~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d10n<-subset(d10n,is.na(year)==FALSE)
d<-d10n
m4<- lm(polity_for10~death*agepre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d10
m5<- lm(polity_for10~death*agepre*personal_lag1 + polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))
marg10_nofe<-margins(m5,at=list(personal_lag1=0:1,agepre=a),vcov=vc,variables="death")


d10<-subset(d10,is.na(year)==FALSE)
d<-d10
m6<- lm(polity_for10~death*agepre*personal_lag1+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))
marg10_fe<-margins(m6,at=list(personal_lag1=0:1,agepre=a),vcov=vc,variables="death")


## Tenure Specification (Appendix, Table 24)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)

d10<-subset(nondem,death_for10==0 )
d10<-subset(d10,is.na(polity_for10)==FALSE & is.na(polity_lag1)==FALSE & is.na(tenpre)==FALSE)
d10p<-subset(d10,personal_lag1==1)
d10n<-subset(d10,personal_lag1==0)

d<-d10p
m1<- lm(polity_for10~death*agepre + tenpre+ polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d10p<-subset(d10p,is.na(year)==FALSE)
d<-d10p
m2<- lm(polity_for10~death*agepre+tenpre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d10n
m3<- lm(polity_for10~death*agepre + tenpre+ polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d10n<-subset(d10n,is.na(year)==FALSE)
d<-d10n
m4<- lm(polity_for10~death*agepre+tenpre+polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d10
m5<- lm(polity_for10~death*agepre*personal_lag1 +tenpre+ polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d10<-subset(d10,is.na(year)==FALSE)
d<-d10
m6<- lm(polity_for10~death*agepre*personal_lag1+tenpre+polity_lag1+ factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))

## Basic Specification, Full Sample (Appendix, Table 25)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)
nondem<-subset(nondem, is.na(death)==FALSE & is.na(agepre)==FALSE & is.na(personal_lag1)==FALSE)


d10<-subset(d10,is.na(polity_lag1)==FALSE)
d10p<-subset(d10,personal_lag1==1)
d10n<-subset(d10,personal_lag1==0)

d<-d10p
m1<- lm(polity_for10~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

d10p<-subset(d10p,is.na(year)==FALSE)
d<-d10p
m2<- lm(polity_for10~death*agepre+ polity_lag1 +factor(year),data=d)
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

d<-d10n
m3<- lm(polity_for10~death*agepre + polity_lag1,data=d)
vc<-vcovCR(m3,cluster=d$ccode,type="CR1")
se3<-sqrt(diag(vc))

d10n<-subset(d10n,is.na(year)==FALSE)
d<-d10n
m4<- lm(polity_for10~death*agepre+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

d<-d10
m5<- lm(polity_for10~death*agepre*personal_lag1 + polity_lag1,data=d)
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

d10<-subset(d10,is.na(year)==FALSE)
d<-d10
m6<- lm(polity_for10~death*agepre*personal_lag1+ polity_lag1+factor(year),data=d)
vc<-vcovCR(m6,cluster=d$ccode,type="CR1")
se6<-sqrt(diag(vc))


####FIGURE FOR H2a (Figure 4 in Main Article)

confi<-function(x,length,pers,lev){
	p<-pers
	confi<-confint(subset(x,personal_lag1==p & agepre==summary(x)$agepre[1]),level=lev)	
	for(i in c(summary(x)$agepre[1:length])){
		a<-i
		confi<-rbind(confi,confint(subset(x,personal_lag1==p & agepre==a))	)
	}
	return(data.frame(confi))
}


png(file="../graphics/fig4.png")
par(mfrow=c(3,2))

len<-nrow(summary(marg1_nofe))
l1<-len/2
l2<-l1+1
confintty0<-confi(marg1_nofe,l1,0,0.9)
confintty1<-confi(marg1_nofe,l1,1,0.9)
plot(x=summary(marg1_nofe)$agepre[1:l1],y=summary(marg1_nofe)$AME[1:l1],pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-10,10),cex=0.8, main="1-Year DV, No Fixed Effects")
segments(	x0=summary(marg1_nofe)$agepre[1:l1],
			y0=confintty0$lower[1:l1],
			x1=summary(marg1_nofe)$agepre[1:l1],
			y1=confintty0$upper[1:l1])
points(x=summary(marg1_nofe)$agepre[l2:len],y=summary(marg1_nofe)$AME[l2:len],pch=20,col="gray")
segments(	x0=summary(marg1_nofe)$agepre[1:l1],
			y0=confintty1$lower[1:l1],
			x1=summary(marg1_nofe)$agepre[1:l1],
			y1=confintty1$upper[1:l1],col="gray")
abline(h=0)
legend(41,9,c("Non-Personalist","Personalist"), pch=19,col=c("black","gray"),text.font=3,cex=0.8)



len<-nrow(summary(marg1_fe))
l1<-len/2
l2<-l1+1
confintty0<-confi(marg1_fe,l1,0,0.9)
confintty1<-confi(marg1_fe,l1,1,0.9)
plot(x=summary(marg1_fe)$agepre[1:l1],y=summary(marg1_fe)$AME[1:l1],pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-10,10),cex=0.8, main="1-Year DV, Fixed Effects")
segments(	x0=summary(marg1_nofe)$agepre[1:l1],
			y0=confintty0$lower[1:l1],
			x1=summary(marg1_nofe)$agepre[1:l1],
			y1=confintty0$upper[1:l1])
points(x=summary(marg1_fe)$agepre[l2:len],y=summary(marg1_fe)$AME[l2:len],pch=20,col="gray")
segments(	x0=summary(marg1_fe)$agepre[1:l1],
			y0=confintty1$lower[1:l1],
			x1=summary(marg1_fe)$agepre[1:l1],
			y1=confintty1$upper[1:l1],col="gray")
abline(h=0)
legend(41,9,c("Non-Personalist","Personalist"), pch=19,col=c("black","gray"),text.font=3,cex=0.8)


len<-nrow(summary(marg5_nofe))
l1<-len/2
l2<-l1+1
confintty0<-confi(marg5_nofe,l1,0,0.9)
confintty1<-confi(marg5_nofe,l1,1,0.9)
plot(x=summary(marg5_nofe)$agepre[1:l1],y=summary(marg5_nofe)$AME[1:l1],pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-10,10),cex=0.8, main="5-Year DV, No Fixed Effects")
segments(	x0=summary(marg5_nofe)$agepre[1:l1],
			y0=confintty0$lower[1:l1],
			x1=summary(marg5_nofe)$agepre[1:l1],
			y1=confintty0$upper[1:l1])
points(x=summary(marg5_nofe)$agepre[l2:len],y=summary(marg5_nofe)$AME[l2:len],pch=20,col="gray")
segments(	x0=summary(marg5_nofe)$agepre[1:l1],
			y0=confintty1$lower[1:l1],
			x1=summary(marg5_nofe)$agepre[1:l1],
			y1=confintty1$upper[1:l1],col="gray")
abline(h=0)
legend(41,9,c("Non-Personalist","Personalist"), pch=19,col=c("black","gray"),text.font=3,cex=0.8)


len<-nrow(summary(marg5_fe))
l1<-len/2
l2<-l1+1
confintty0<-confi(marg5_fe,l1,0,0.9)
confintty1<-confi(marg5_fe,l1,1,0.9)
plot(x=summary(marg5_fe)$agepre[1:l1],y=summary(marg5_fe)$AME[1:l1],pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-10,10),cex=0.8, main="5-Year DV, Fixed Effects")
segments(	x0=summary(marg5_fe)$agepre[1:l1],
			y0=confintty0$lower[1:l1],
			x1=summary(marg5_fe)$agepre[1:l1],
			y1=confintty0$upper[1:l1])
points(x=summary(marg5_fe)$agepre[l2:len],y=summary(marg5_fe)$AME[l2:len],pch=20,col="gray")
segments(	x0=summary(marg5_fe)$agepre[1:l1],
			y0=confintty1$lower[1:l1],
			x1=summary(marg5_fe)$agepre[1:l1],
			y1=confintty1$upper[1:l1],col="gray")
abline(h=0)
legend(41,9,c("Non-Personalist","Personalist"), pch=19,col=c("black","gray"),text.font=3,cex=0.8)



len<-nrow(summary(marg10_nofe))
l1<-len/2
l2<-l1+1
confintty0<-confi(marg10_nofe,l1,0,0.9)
confintty1<-confi(marg10_nofe,l1,1,0.9)
plot(x=summary(marg10_nofe)$agepre[1:l1],y=summary(marg10_nofe)$AME[1:l1],pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-10,10),cex=0.8, main="10-Year DV, No Fixed Effects")
segments(	x0=summary(marg10_nofe)$agepre[1:l1],
			y0=confintty0$lower[1:l1],
			x1=summary(marg10_nofe)$agepre[1:l1],
			y1=confintty0$upper[1:l1])
points(x=summary(marg10_nofe)$agepre[l2:len],y=summary(marg10_nofe)$AME[l2:len],pch=20,col="gray")
segments(	x0=summary(marg10_nofe)$agepre[1:l1],
			y0=confintty1$lower[1:l1],
			x1=summary(marg10_nofe)$agepre[1:l1],
			y1=confintty1$upper[1:l1],col="gray")
abline(h=0)
legend(41,9,c("Non-Personalist","Personalist"), pch=19,col=c("black","gray"),text.font=3,cex=0.8)


len<-nrow(summary(marg10_fe))
l1<-len/2
l2<-l1+1
confintty0<-confi(marg10_fe,l1,0,0.9)
confintty1<-confi(marg10_fe,l1,1,0.9)
plot(x=summary(marg10_fe)$agepre[1:l1],y=summary(marg10_fe)$AME[1:l1],pch=20,xlab="Age",ylab="Average Marginal Effect of Death",ylim=c(-10,10),cex=0.8, main="10-Year DV, Fixed Effects")
segments(	x0=summary(marg10_fe)$agepre[1:l1],
			y0=confintty0$lower[1:l1],
			x1=summary(marg10_fe)$agepre[1:l1],
			y1=confintty0$upper[1:l1])
points(x=summary(marg10_fe)$agepre[l2:len],y=summary(marg10_fe)$AME[l2:len],pch=20,col="gray")
segments(	x0=summary(marg10_fe)$agepre[1:l1],
			y0=confintty1$lower[1:l1],
			x1=summary(marg10_fe)$agepre[1:l1],
			y1=confintty1$upper[1:l1],col="gray")
abline(h=0)
legend(41,9,c("Non-Personalist","Personalist"), pch=19,col=c("black","gray"),text.font=3,cex=0.8)

dev.off()

```

```{r}

### Replication of Figure 5

#Ultimate fate of dictators, by regime type (Figure 5 in Main Article)

nondem<-subset(data,polity_lag1<0)
nondem<-subset(nondem, is.na(death)==FALSE )
subby<-nondem
subby$keep<-subby$otherexit
subby$keep<-ifelse(subby$death==1,1,subby$keep)
subby<-subset(subby,keep==1)


#subby<-merge(subby,leaders,all.x=TRUE,all.y=FALSE)

death<-subset(nondem,death==1)
age<-quantile(death$agepre,c(0.25,0.5,0.75),na.rm=TRUE)

age0<-subset(subby,agepre<=54)

age25<-subset(subby,agepre>54)
age25<-subset(age25,agepre<=64)

age50<-subset(subby,subby$agepre>64)
age50<-subset(age50,age50$agepre<=73)

age75<-subset(subby,agepre>73)


#non personalist

age0x<-subset(age0,personal==0)
age25x<-subset(age25,personal==0)
age50x<-subset(age50,personal==0)
age75x<-subset(age75,personal==0)

death0<-nrow(subset(age0x,death==1))
s1<-subset(age0x,democracy==1)
s2<-subset(age0x,democracy==0)
irreg0<-nrow(subset(s2,otherirreg==1))
reg0<-subset(s2,otherexit==1)
reg0<-nrow(subset(reg0,otherirreg==0))
dem0<-nrow(subset(s1,death==0))

death25<-nrow(subset(age25x,death==1))
s1<-subset(age25x,democracy==1)
s2<-subset(age25x,democracy==0)
irreg25<-nrow(subset(s2,otherirreg==1))
reg25<-subset(s2,otherexit==1)
reg25<-nrow(subset(reg25,otherirreg==0))
dem25<-nrow(subset(s1,death==0))

death50<-nrow(subset(age50x,death==1))
s1<-subset(age50x,democracy==1)
s2<-subset(age50x,democracy==0)
irreg50<-nrow(subset(s2,otherirreg==1))
reg50<-subset(s2,otherexit==1)
reg50<-nrow(subset(reg50,otherirreg==0))
dem50<-nrow(subset(s1,death==0))

death75<-nrow(subset(age75x,death==1))
s1<-subset(age75x,democracy==1)
s2<-subset(age75x,democracy==0)
irreg75<-nrow(subset(s2,otherirreg==1))
reg75<-subset(s2,otherexit==1)
reg75<-nrow(subset(reg75,otherirreg==0))
dem75<-nrow(subset(s1,death==0))

death<-c(death0,death25,death50,death75)
irreg<-c(irreg0,irreg25,irreg50,irreg75)
reg<-c(reg0,reg25,reg50,reg75)
dem<-c(dem0,dem25,dem50,dem75)

noper_exit<-data.frame(death,irreg,reg,dem)


# personal
age0x<-subset(age0,personal==1)
age25x<-subset(age25,personal==1)
age50x<-subset(age50,personal==1)
age75x<-subset(age75,personal==1)

death0<-nrow(subset(age0x,death==1))
s1<-subset(age0x,democracy==1)
s2<-subset(age0x,democracy==0)
irreg0<-nrow(subset(s2,otherirreg==1))
reg0<-subset(s2,otherexit==1)
reg0<-nrow(subset(reg0,otherirreg==0))
dem0<-nrow(subset(s1,death==0))

death25<-nrow(subset(age25x,death==1))
s1<-subset(age25x,democracy==1)
s2<-subset(age25x,democracy==0)
irreg25<-nrow(subset(s2,otherirreg==1))
reg25<-subset(s2,otherexit==1)
reg25<-nrow(subset(reg25,otherirreg==0))
dem25<-nrow(subset(s1,death==0))

death50<-nrow(subset(age50x,death==1))
s1<-subset(age50x,democracy==1)
s2<-subset(age50x,democracy==0)
irreg50<-nrow(subset(s2,otherirreg==1))
reg50<-subset(s2,otherexit==1)
reg50<-nrow(subset(reg50,otherirreg==0))
dem50<-nrow(subset(s1,death==0))

death75<-nrow(subset(age75x,death==1))
s1<-subset(age75x,democracy==1)
s2<-subset(age75x,democracy==0)
irreg75<-nrow(subset(s2,otherirreg==1))
reg75<-subset(s2,otherexit==1)
reg75<-nrow(subset(reg75,otherirreg==0))
dem75<-nrow(subset(s1,death==0))

death<-c(death0,death25,death50,death75)
irreg<-c(irreg0,irreg25,irreg50,irreg75)
reg<-c(reg0,reg25,reg50,reg75)
dem<-c(dem0,dem25,dem50,dem75)

per_exit<-data.frame(death,irreg,reg,dem)


y<-per_exit

x0<-sum(y[1,])+sum(y[2,])+sum(y[3,])+sum(y[4,])
x25<-sum(y[2,])+sum(y[3,])+sum(y[4,])
x50<-sum(y[3,])+sum(y[4,])
x75<-sum(y[4,])

a0<-c(sum(y[,1])/x0,sum(y[,2])/x0,sum(y[,3])/x0,sum(y[,4])/x0)
y<-y[-1,]
a25<-c(sum(y[,1])/x25,sum(y[,2])/x25,sum(y[,3])/x25,sum(y[,4])/x25)
y<-y[-1,]
a50<-c(sum(y[,1])/x50,sum(y[,2])/x50,sum(y[,3])/x50,sum(y[,4])/x50)
y<-y[-1,]
a75<-c(sum(y[,1])/x75,sum(y[,2])/x75,sum(y[,3])/x75,sum(y[,4])/x75)

per_perc<-rbind(a0,a25,a50,a75)
colnames(per_perc)<-c("death","irreg","reg","dem")

y<-noper_exit

x0<-sum(y[1,])+sum(y[2,])+sum(y[3,])+sum(y[4,])
x25<-sum(y[2,])+sum(y[3,])+sum(y[4,])
x50<-sum(y[3,])+sum(y[4,])
x75<-sum(y[4,])

a0<-c(sum(y[,1])/x0,sum(y[,2])/x0,sum(y[,3])/x0,sum(y[,4])/x0)
y<-y[-1,]
a25<-c(sum(y[,1])/x25,sum(y[,2])/x25,sum(y[,3])/x25,sum(y[,4])/x25)
y<-y[-1,]
a50<-c(sum(y[,1])/x50,sum(y[,2])/x50,sum(y[,3])/x50,sum(y[,4])/x50)
y<-y[-1,]
a75<-c(sum(y[,1])/x75,sum(y[,2])/x75,sum(y[,3])/x75,sum(y[,4])/x75)

noper_perc<-rbind(a0,a25,a50,a75)
colnames(noper_perc)<-c("death","irreg","reg","dem")

personalist<-c(per_perc[3,1],per_perc[3,2],per_perc[3,3],per_perc[3,4])
nonpersonalist<-c(noper_perc[3,1],noper_perc[3,2],noper_perc[3,3],noper_perc[3,4])

plotty<-data.frame(personalist, nonpersonalist)
plotty<-as.matrix(plotty)

png(file="../graphics/fig5.png")
barplot(height=plotty,col=c("black","darkgrey","lightgrey","white"), beside=T, legend=c("death","irreg","reg","dem"), ylim=c(0,0.6))
dev.off()


```

```{r}

### Replication of Figure 6

####  H2b Analyses: Effect of leader age on likelihood of removal


### Logit analyses (Appendix, Table 26)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)


per<-subset(nondem,personal_lag1==1)
mil<-subset(nondem,military_lag1==1)
mon<-subset(nondem,monarchy_lag1==1)
par<-subset(nondem,party_lag1==1)


d<-nondem
m1 <- glm(allcoup_bin~agepre+personal_lag1 + polity_lag1 + allcoup_count_lag10,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

m2 <- glm(allcoup_bin~agepre*personal_lag1 + polity_lag1 + allcoup_count_lag10,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))
plotty1<-m2

m3<-clogit(allcoup_bin~agepre*personal_lag1 + polity_lag1+allcoup_count_lag10+strata(year),data=nondem)
se3<-sqrt(diag(vcov(m3)))


m4 <- glm(otherirreg~agepre+personal_lag1  + polity_lag1+ allcoup_count_lag10,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))


m5 <- glm(otherirreg~agepre*personal_lag1  + polity_lag1+ allcoup_count_lag10 ,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))
plotty2<-m5

m6<-clogit(otherirreg~agepre*personal_lag1+ polity_lag1+ allcoup_count_lag10  +strata(year),data=nondem)
se6<-sqrt(diag(vcov(m6)))


##Logit analyses, tenure sepecification (Appendix, Table 27)

nondem<-subset(data,military_lag1==1 |monarchy_lag1==1|personal_lag1==1|party_lag1==1)


per<-subset(nondem,personal_lag1==1)
mil<-subset(nondem,military_lag1==1)
mon<-subset(nondem,monarchy_lag1==1)
par<-subset(nondem,party_lag1==1)


d<-nondem
m1 <- glm(allcoup_bin~agepre+personal_lag1 + tenpre+polity_lag1 + allcoup_count_lag10,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m1,cluster=d$ccode,type="CR1")
se1<-sqrt(diag(vc))

m2 <- glm(allcoup_bin~agepre*personal_lag1 + tenpre+polity_lag1 + allcoup_count_lag10,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m2,cluster=d$ccode,type="CR1")
se2<-sqrt(diag(vc))

m3<-clogit(allcoup_bin~agepre*personal_lag1 + tenpre+polity_lag1+allcoup_count_lag10+strata(year),data=nondem)
se3<-sqrt(diag(vcov(m3)))

m4 <- glm(otherirreg~agepre+personal_lag1  + tenpre+polity_lag1+allcoup_count_lag10,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m4,cluster=d$ccode,type="CR1")
se4<-sqrt(diag(vc))

m5 <- glm(otherirreg~agepre*personal_lag1  + tenpre+polity_lag1+allcoup_count_lag10 ,data=nondem,family=binomial(link=logit))
vc<-vcovCR(m5,cluster=d$ccode,type="CR1")
se5<-sqrt(diag(vc))

m6<-clogit(otherirreg~agepre*personal_lag1+ tenpre+polity_lag1 +allcoup_count_lag10 +strata(year),data=nondem)
se6<-sqrt(diag(vcov(m3)))

## Figure for H2b (Figure 6 in Main Article)
png(file="../graphics/fig6.png")
par(mfrow=c(2,1))

p1<-mean(nondem$polity_lag1,na.rm=TRUE)
coup<-mean(nondem$allcoup_count_lag10,na.rm=TRUE)
nondemd<-subset(nondem,death==1)
age<-seq(quantile(nondemd$agepre,0.1, na.rm=TRUE),quantile(nondemd$agepre,0.9,na.rm=TRUE),1)

eff1<-predict(plotty1, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=1),type="link",se.fit=TRUE)
up <- eff1$fit + 2*eff1$se.fit
low <- eff1$fit - 2*eff1$se.fit
upper_p<- exp(up)/(1+exp(up))
lower_p<- exp(low)/(1+exp(low))
eff1_p<-predict(plotty1, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=1),type="response")

eff1<-predict(plotty1, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=0),type="link",se.fit=TRUE)
up <- eff1$fit + 2*eff1$se.fit
low <- eff1$fit - 2*eff1$se.fit
upper_n <- exp(up)/(1+exp(up))
lower_n<- exp(low)/(1+exp(low))
eff1_n<-predict(plotty1, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=0),type="response")


plot(age,eff1_p,ylim=c(0,0.4),type="l",ylab="Predicted Probability",xlab="Leader Age",main="DV: Attempted Coup")
cord.x<-c(age[1],age[1],age,age[length(age)],age[length(age)],rev(age))
cord.y<-c(upper_p[1],lower_p[1],lower_p,lower_p[length(age)],upper_p[length(age)],rev(upper_p))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.6))
lines(age,eff1_n)
cord.x<-c(age[1],age[1],age,age[length(age)],age[length(age)],rev(age))
cord.y<-c(upper_n[1],lower_n[1],lower_n,lower_n[length(age)],upper_n[length(age)],rev(upper_n))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.3))
legend(52,0.385,c("Personalist","Non-Personalist"), pch=19,col=c(rgb(0,0,0,alpha=0.6),rgb(0,0,0,alpha=0.3)),text.font=3,cex=0.8)


p1<-mean(nondem$polity_lag1,na.rm=TRUE)
coup<-mean(nondem$allcoup_count_lag10,na.rm=TRUE)
nondemd<-subset(nondem,death==1)
age<-seq(quantile(nondemd$agepre,0.1, na.rm=TRUE),quantile(nondemd$agepre,0.9,na.rm=TRUE),1)

eff1<-predict(plotty2, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=1),type="link",se.fit=TRUE)
up <- eff1$fit + 2*eff1$se.fit
low <- eff1$fit - 2*eff1$se.fit
upper_p<- exp(up)/(1+exp(up))
lower_p<- exp(low)/(1+exp(low))
eff1_p<-predict(plotty2, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=1),type="response")

eff1<-predict(plotty2, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=0),type="link",se.fit=TRUE)
up <- eff1$fit + 2*eff1$se.fit
low <- eff1$fit - 2*eff1$se.fit
upper_n <- exp(up)/(1+exp(up))
lower_n<- exp(low)/(1+exp(low))
eff1_n<-predict(plotty2, newdata=data.frame(polity_lag1=p1,allcoup_count_lag10=coup,agepre=age,personal_lag1=0),type="response")


plot(age,eff1_p,ylim=c(0,0.4),type="l",ylab="Predicted Probability",xlab="Leader Age",main="DV: Irregular Exit")
cord.x<-c(age[1],age[1],age,age[length(age)],age[length(age)],rev(age))
cord.y<-c(upper_p[1],lower_p[1],lower_p,lower_p[length(age)],upper_p[length(age)],rev(upper_p))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.6))
lines(age,eff1_n)
cord.x<-c(age[1],age[1],age,age[length(age)],age[length(age)],rev(age))
cord.y<-c(upper_n[1],lower_n[1],lower_n,lower_n[length(age)],upper_n[length(age)],rev(upper_n))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.3))
legend(52,0.385,c("Personalist","Non-Personalist"), pch=19,col=c(rgb(0,0,0,alpha=0.6),rgb(0,0,0,alpha=0.3)),text.font=3,cex=0.8)

dev.off()

```

```{r}

### Replication of Figure 7

#### H2b: Survival analysis 

datasurv<-read.csv("../raw-data/survdata_190123.csv")
datasurv<-datasurv[-c(1)]
datasurv$start<-datasurv$tenpre
datasurv$stop<-datasurv$start+1


## DV: Coup Attempts (Appendix, Table 28)
nondemsurv<-subset(datasurv,polity_lag1<0)

m1<-coxph(Surv(start,stop,allcoup_bin)~agepre+personal_lag1+polity_lag1,data=nondemsurv)
m2<-coxph(Surv(start,stop,allcoup_bin)~agepre*personal_lag1+polity_lag1,data=nondemsurv)
m3<-coxph(Surv(start,stop,allcoup_bin)~agepre*personal_lag1 +polity_lag1+ allcoup_count_lag10,data=nondemsurv)
m4<-coxph(Surv(start,stop,allcoup_bin)~agepre+personal_lag1+polity_lag1+factor(year),data=nondemsurv)
m5<-coxph(Surv(start,stop,allcoup_bin)~agepre*personal_lag1+polity_lag1+factor(year),data=nondemsurv)
m6<-coxph(Surv(start,stop,allcoup_bin)~agepre*personal_lag1 +polity_lag1+factor(year)+ allcoup_count_lag10,data=nondemsurv)

## DV: Coup Attempts (Appendix, Table 29)
m7<-coxph(Surv(start,stop,otherirreg)~agepre+personal_lag1+polity_lag1,data=nondemsurv)
m8<-coxph(Surv(start,stop,otherirreg)~agepre*personal_lag1+polity_lag1,data=nondemsurv)
m9<-coxph(Surv(start,stop,otherirreg)~agepre*personal_lag1+polity_lag1+allcoup_count_lag10,data=nondemsurv)
m10<-coxph(Surv(start,stop,otherirreg)~agepre+personal_lag1+polity_lag1+factor(year),data=nondemsurv)
m11<-coxph(Surv(start,stop,otherirreg)~agepre*personal_lag1+polity_lag1+factor(year),data=nondemsurv)
m12<-coxph(Surv(start,stop,otherirreg)~agepre*personal_lag1+polity_lag1+allcoup_count_lag10+factor(year),data=nondemsurv)



##H2b Survival Analysis Figure (Figure 7 in Appendix)

nondemsurvd<-subset(nondemsurv,death==1)	
al<-round(quantile(nondemsurvd$agepre,0.1, na.rm=TRUE))
ah<-round(quantile(nondemsurvd$agepre,0.9,na.rm=TRUE))

nondem<-subset(data,polity_lag1<0)	
nondemd<-subset(nondem,death==1)	
al<-round(quantile(nondemd$agepre,0.1, na.rm=TRUE))
ah<-round(quantile(nondemd$agepre,0.9,na.rm=TRUE))


png(file="../graphics/fig7.png")
par(mfrow=c(2,2))

xmax<-20

newdata_young<-data.frame(agepre=al, polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE),personal_lag1=0,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_young<-survfit(m3,newdata=newdata_young,conf.type="plain",conf.int=0.9)
newdata_old<-data.frame(agepre=ah,polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE), personal_lag1=0,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_old<-survfit(m3,newdata=newdata_old,conf.type="plain",conf.int=0.90)
plot(fit_young$time[1:xmax], fit_young$surv[1:xmax],lty=1,main = "DV: Coup Attempt",xlab="years in office",ylab="survival= no coup",type="l",ylim=c(0,1.2),xlim=c(fit_young$time[1],fit_young$time[xmax]),yaxt="n")
axis(2,at=c(0,0.2,0.4,0.6,0.8,1),labels=c("0","0.2","0.4","0.6","0.8","1"),las=2)
cord.x<-c(fit_young$time[1],fit_young$time[1],fit_young$time[1:xmax],fit_young$time[xmax],fit_young$time[xmax],rev(fit_young$time[1:xmax]))
cord.y<-c(fit_young$upper[1],fit_young$lower[1],fit_young$lower[1:xmax],fit_young$lower[xmax],fit_young$upper[xmax],rev(fit_young$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.6))
lines(fit_old$time[1:xmax], fit_old$surv[1:xmax])
cord.x<-c(fit_old$time[1],fit_old$time[1],fit_old$time[1:xmax],fit_old$time[xmax],fit_old$time[xmax],rev(fit_old$time[1:xmax]))
cord.y<-c(fit_old$upper[1],fit_old$lower[1],fit_old$lower[1:xmax],fit_old$lower[xmax],fit_old$upper[xmax],rev(fit_old$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.3))
abline(h=1.1)
legend(fit_old$time[xmax]-6,1.05,legend=c("Young","Old"),pch=19,col=c(rgb(0,0,0,alpha=0.6),rgb(0,0,0,alpha=0.3)))
text(3.5,1.17,c("Non-Personalist Regimes"),vfont=c("sans serif","bold italic"),pos=4)

newdata_young<-data.frame(agepre=al, polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE),personal_lag1=0,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_young<-survfit(m9,newdata=newdata_young,conf.type="plain",conf.int=0.9)
newdata_old<-data.frame(agepre=ah,polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE), personal_lag1=0,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_old<-survfit(m9,newdata=newdata_old,conf.type="plain",conf.int=0.90)
plot(fit_young$time[1:xmax], fit_young$surv[1:xmax],lty=1,main = "DV: Irregular Exit",xlab="years in office",ylab="survival= no irregular exit",type="l",ylim=c(0,1.2),xlim=c(fit_young$time[1],fit_young$time[xmax]),yaxt="n")
axis(2,at=c(0,0.2,0.4,0.6,0.8,1),labels=c("0","0.2","0.4","0.6","0.8","1"),las=2)
cord.x<-c(fit_young$time[1],fit_young$time[1],fit_young$time[1:xmax],fit_young$time[xmax],fit_young$time[xmax],rev(fit_young$time[1:xmax]))
cord.y<-c(fit_young$upper[1],fit_young$lower[1],fit_young$lower[1:xmax],fit_young$lower[xmax],fit_young$upper[xmax],rev(fit_young$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.6))
lines(fit_old$time[1:xmax], fit_old$surv[1:xmax])
cord.x<-c(fit_old$time[1],fit_old$time[1],fit_old$time[1:xmax],fit_old$time[xmax],fit_old$time[xmax],rev(fit_old$time[1:xmax]))
cord.y<-c(fit_old$upper[1],fit_old$lower[1],fit_old$lower[1:xmax],fit_old$lower[xmax],fit_old$upper[xmax],rev(fit_old$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.3))
abline(h=1.1)
legend(fit_old$time[xmax]-6,1.05,legend=c("Young","Old"),pch=19,col=c(rgb(0,0,0,alpha=0.6),rgb(0,0,0,alpha=0.3)))
text(3.5,1.17,c("Non-Personalist Regimes"),vfont=c("sans serif","bold italic"),pos=4)


newdata_young<-data.frame(agepre=al, polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE),personal_lag1=1,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_young<-survfit(m9,newdata=newdata_young,conf.type="plain",conf.int=0.9)
newdata_old<-data.frame(agepre=ah,polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE), personal_lag1=1,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_old<-survfit(m9,newdata=newdata_old,conf.type="plain",conf.int=0.90)
plot(fit_young$time[1:xmax], fit_young$surv[1:xmax],lty=1,main = "",xlab="years in office",ylab="survival= no coup",type="l",ylim=c(0,1.2),xlim=c(fit_young$time[1],fit_young$time[xmax]),yaxt="n")
axis(2,at=c(0,0.2,0.4,0.6,0.8,1),labels=c("0","0.2","0.4","0.6","0.8","1"),las=2)
cord.x<-c(fit_young$time[1],fit_young$time[1],fit_young$time[1:xmax],fit_young$time[xmax],fit_young$time[xmax],rev(fit_young$time[1:xmax]))
cord.y<-c(fit_young$upper[1],fit_young$lower[1],fit_young$lower[1:xmax],fit_young$lower[xmax],fit_young$upper[xmax],rev(fit_young$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.6))
lines(fit_old$time[1:xmax], fit_old$surv[1:xmax])
cord.x<-c(fit_old$time[1],fit_old$time[1],fit_old$time[1:xmax],fit_old$time[xmax],fit_old$time[xmax],rev(fit_old$time[1:xmax]))
cord.y<-c(fit_old$upper[1],fit_old$lower[1],fit_old$lower[1:xmax],fit_old$lower[xmax],fit_old$upper[xmax],rev(fit_old$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.3))
abline(h=1.1)
legend(fit_old$time[xmax]-6,1.05,legend=c("Young","Old"),pch=19,col=c(rgb(0,0,0,alpha=0.6),rgb(0,0,0,alpha=0.3)))
text(5,1.17,c("Personalist Regimes"),vfont=c("sans serif","bold italic"),pos=4)

newdata_young<-data.frame(agepre=al, polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE),personal_lag1=1,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_young<-survfit(m9,newdata=newdata_young,conf.type="plain",conf.int=0.9)
newdata_old<-data.frame(agepre=ah,polity_lag1=mean(nondemsurv$polity_lag1,na.rm=TRUE), personal_lag1=1,allcoup_count_lag10=mean(nondemsurv$allcoup_count_lag10,na.rm=TRUE))
fit_old<-survfit(m9,newdata=newdata_old,conf.type="plain",conf.int=0.90)
plot(fit_young$time[1:xmax], fit_young$surv[1:xmax],lty=1,main = "",xlab="years in office",ylab="survival= no irregular exit",type="l",ylim=c(0,1.2),xlim=c(fit_young$time[1],fit_young$time[xmax]),yaxt="n")
axis(2,at=c(0,0.2,0.4,0.6,0.8,1),labels=c("0","0.2","0.4","0.6","0.8","1"),las=2)
cord.x<-c(fit_young$time[1],fit_young$time[1],fit_young$time[1:xmax],fit_young$time[xmax],fit_young$time[xmax],rev(fit_young$time[1:xmax]))
cord.y<-c(fit_young$upper[1],fit_young$lower[1],fit_young$lower[1:xmax],fit_young$lower[xmax],fit_young$upper[xmax],rev(fit_young$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.6))
lines(fit_old$time[1:xmax], fit_old$surv[1:xmax])
cord.x<-c(fit_old$time[1],fit_old$time[1],fit_old$time[1:xmax],fit_old$time[xmax],fit_old$time[xmax],rev(fit_old$time[1:xmax]))
cord.y<-c(fit_old$upper[1],fit_old$lower[1],fit_old$lower[1:xmax],fit_old$lower[xmax],fit_old$upper[xmax],rev(fit_old$upper[1:xmax]))
polygon(cord.x,cord.y,col=rgb(0,0,0,alpha=0.3))
abline(h=1.1)
legend(fit_old$time[xmax]-6,1.05,legend=c("Young","Old"),pch=19,col=c(rgb(0,0,0,alpha=0.6),rgb(0,0,0,alpha=0.3)))
text(1,1.17,c("Personalist Regimes"),vfont=c("sans serif","bold italic"),pos=4)

dev.off()

```


